spring:
  application:
    name: payment-service
  profiles:
    default: static-discovery

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

